### PR TITLE
implement Zero for Quantity when the backend supports Zero

### PR DESCRIPTION
**Pull request by radix**
Here we go, my first try at a trivial trait implementation for uom.

Please let me know if there are any problems or improvements I can make!

### CODE REVIEW

**Comment by iliekturtles** [comment]
Implementation looks good. Some minor changes then I'll merge!

- Squash the commits. Change the message to something like "Implement `num::Zero`.\n\nPart of #26."
- Move the implementation in `system.rs` below `RemAssign`.
- `tests.rs`
  - Put a blank line beneath `let z = ...`
  - Use `Test::assert_eq(V::Zero, z.value);`

**Comment by radix** [comment]
FYI I believe you can squash the commits as part of merge with github while you're merging it, though it may be a setting that needs to be enabled in your repository. Regardless I will squash as you requested :)

**Comment by radix** [comment]
hooray, forgot to run `git add` before `git commit --amend` ;P this test pass should hopefully work...

**Comment by iliekturtles** [comment]
Replaced literal `0.0` with `V::zero()` and merged. Thanks!

**Pull request closed without merging**
