### PR TITLE
Information quantities

### LINKED ISSUE #31: Add support for bytes?
Would support for 'bytes' be within scope for this library? Would that work out well with using f32 / f64 storage? It seems like perhaps using `u64` for bytes, but floating point for all larger units might be useful?

### PR DESCRIPTION
**Pull request by Lukazoid**
Closes #31, #154

### CODE REVIEW

**Comment by iliekturtles** [comment]
Awesome! Thanks for the PR. I'll start reviewing this week. You can ignore the 1.28.0 build failures for the moment. See #157.

**Comment by Lukazoid** [comment]
Will fix the fmt and clippy errors tomorrow.

**Comment by Lukazoid** [comment]
Any idea why clippy fails with warnings around my use of `InformationKind` but the use of `AngleKind` doesn't appear to? I can't figure out what's different.

**Comment by iliekturtles** [comment]
You just need the `dyn` keyword and some parenthesis. I recently enabled the lint that requires this.

https://github.com/iliekturtles/uom/blob/c5dc8b43b17051e3ecc3c05140451d8d935b6475/src/si/angle.rs#L15

**Comment by iliekturtles** [comment]
First pass at a review is complete. I still need to go through and review each of the details to validate conversion factors and descriptions.

 * Rebase your changes on top of the latest `master` to get a number of fixes. The issue with the 1.28.0 build failures have been resolved (you may need to `cargo update`) locally. There are a couple uses of `crate::` in these changes that need to be resolved.
 * `unit_coef` and `unit_const` should be able to be moved out of the `quantity!` macro. I don't think there is a need to generate these for each quantity.
 * information.rs
   * Remove the blank line 17 and 55. Remove trailing whitespace from 53.
   * Should the abbreviation for `deciban` be `dHart`?
 * information_rate.rs
    * Change line 6 to reference "information rate" instead of "baud rate." Perhaps note in one of the doc comments the equivalence?
    * Wrap 45 and 46 at 100 characters.
    * Add test cases for all the information rate units.
 * mod.rs
    * Remove the blank line 284.
 * prefix.rs
    * Note that SI and binary prefixes are implemented in the macro's doc comment.
    * Change line 36 to `// Binary prefixes.`

**Comment by Lukazoid** [comment]
@iliekturtles Thanks, I will get on to those changes this evening after work 👍

**Comment by Lukazoid** [comment]
Seems my macros don't work for the bigint storage types, will try and figure out a solution.

**Comment by iliekturtles** [comment]
I'll take a look tomorrow as well. It may be a limitation of how the `quantity!` macro is setup so don't put too much time into it.

**Comment by iliekturtles** [comment]
Conversion factors for some underlying storage types are currently (I want to change this in v2.0.0) first converted into `f64` and then into the resulting type such as `Ratio<BigInt>`. Using the conversion factor of another unit returns the resulting the resulting type while the `quantity!` internals are still working as `f64`.

Using the conversion factor for the unit as `f64` may fix the error but may also introduce some precision issues. Give it a try and we can't get that working I think it's OK to table this for the time being and revisit after v1.0.0 is released.

**Comment by iliekturtles** [comment]
I did another round of review and pushed changes to a branch in my repo: https://github.com/Lukazoid/uom/compare/information_quantities...iliekturtles:Lukazoid-information_quantities. If you want to review/apply to your branch/squash I think we can merge!

 * Fixed `mebi` prefix (was `mibi`).
 * Re-ordered units from large to small to match conventions of other quantities.
 * Ended up removing the `unit_coef!` and `unit_const!` macros. Issues with other underlying storage types like `BigInt` aren't worth holding up the rest of this PR.
 * Cleaned up some comments.

**Comment by Lukazoid** [comment]
Thanks @iliekturtles I have done this.

**Comment by iliekturtles** [comment]
Awesome! I'm planning do a final review tonight and then merge.

**Pull request merged**
