### PR TITLE
Add quantity: AngularAbsement

### PR DESCRIPTION
**Pull request by professoralex13**
Adds an AngleKind version of Absement

### CODE REVIEW

**Comment by iliekturtles** [comment]
Thanks for the PR! I've started the tests and a quick scan of the code looks good. Will try to do a more thorough review later today.

**Comment by iliekturtles** [comment]
I pushed some formatting and typo fixes to your fork. Could you review, squash, and set an updated commit message. Something like the one on my commit.

**Comment by professoralex13** [comment]
> I pushed some formatting and typo fixes to your fork. Could you review, squash, and set an updated commit message. Something like the one on my commit.

sounds good, have done that

**Comment by iliekturtles** [comment]
Merged! Thanks again for the PR.

**Pull request merged**
