### PR TITLE
chore: Update to static_assertions to 1

### PR DESCRIPTION
**Pull request by eclipseo**
Signed-off-by: Robert-André Mauchin <zebob.m@gmail.com>

PR to replace #169

### CODE REVIEW

**Comment by eclipseo** [comment]
This bump MSRV to 1.37 at least so you may want to delay that.

**Comment by iliekturtles** [comment]
Yeah, I'd like to delay bumping the MSRV. Is it possible to use more recent versions of either dependencies on 1.31?

**Comment by eclipseo** [comment]
Quickcheck is good, it's static_assertions > 1 that needs 1.37.

**Comment by iliekturtles** [comment]
I just did some more digging and unfortunately neither `quickcheck` nor `static_assertions` can be upgraded without an accompanying MSRV (minimum supported Rust version) update for `uom` at the same time. I'm closing the PR since I don't want to bump the MSRV yet. Thank you for the PR!

**Pull request closed without merging**
