### PR TITLE
feat: add absement quantity and units

### PR DESCRIPTION
**Pull request by nick-pascucci-spire**
[Absement](https://en.wikipedia.org/wiki/Absement) is a measure of the time-integrated displacement of an object. It is measured as a product of length and time. This PR adds an `absement` module to the SI system along with corresponding units.

### CODE REVIEW

**Comment by iliekturtles** [comment]
Thanks for the PR! I'm going to try to review today.

**Comment by iliekturtles** [comment]
Changes look really good. Only change that is really needed is wrapping one of the long lines:

```diff
diff --git a/src/si/absement.rs b/src/si/absement.rs
index a4b56a8..59bcaf1 100644
--- a/src/si/absement.rs
+++ b/src/si/absement.rs
@@ -74,7 +74,8 @@ mod tests {

         #[test]
         fn check_dimension() {
-            let _: Absement<V> = Length::new::<l::meter>(V::one()) * Time::new::<t::second>(V::one());
+            let _: Absement<V> = Length::new::<l::meter>(V::one())
+                * Time::new::<t::second>(V::one());
         }

         #[test]
```

Are there any other common units that should be added right now? You're also welcome to squash your commits into one.

**Comment by nick-pascucci-spire** [comment]
> Only change that is really needed is wrapping one of the long lines

Sure thing, 549c53e should handle that.

> Are there any other common units that should be added right now?

I think the most common ones are likely to be m*s, mm*s, km*s, ft*s, and km*h. This quantity is most likely to be used for PID control of actuators, so unless someone is doing something quite exotic these should be sufficient.

> You're also welcome to squash your commits into one.

No problem, I'll squash and force push now.

**Comment by iliekturtles** [comment]
Excellent! Will merge once the build passes.

**Comment by nick-pascucci-spire** [comment]
Thanks for reviewing, and for `uom`! It's a great library.

**Pull request merged**
