### PR TITLE
WIP: stab at PartialEq + PartialOrd

### PR DESCRIPTION
**Pull request by radix**
It's a mess, I am committing & pushing because I'm being kicked out of a coffee shop! :) If you already have an implementation of this in progress I can just delete this PR, I just threw it together in a few minutes in case it'd help! But if you don't, I can finish cleaning it up in a couple hours.

### CODE REVIEW

**Comment by radix** [comment]
honestly, it's a pity that #[derive] doesn't work -- it does generate an implementation, but it puts bounds on D and U having PartialEq and PartialOrd as well. oh well.

**Comment by iliekturtles** [comment]
I started working on `PartialEq` in my [`dev`](https://github.com/iliekturtles/uom/commits/dev) branch. Feel free to take any of those changes. I'm not sure how much time I'll have this weekend so you may be able to get to it sooner. Currently the `HEAD` commit mixes `impl PartialEq for Quantity` with `impl Test for Quantity`. I think my next step was to split the commit in two, but it's been a few days since I've worked on it.

**Comment by radix** [comment]
aha! I literally just noticed your commits there a minute ago.

I currently have this one implementing PartialEq, PartialOrd, Ord, and Eq (of course only when the backends implement those traits). Are you okay with those for trait implementations being in a single PR, or would you like them split?

**Comment by iliekturtles** [comment]
Single PR is fine. Just separate each `impl` into a separate commit.

**Comment by radix** [comment]
sure thing.

**Comment by iliekturtles** [comment]
Made some fixes and split the `PartialEq` and `Test` `impl`s into separate commits in my dev branch.

**Comment by iliekturtles** [comment]
Resolved by changes just pushed to `master` to implement `PartialEq`, `Eq`, `PartialOrd`, and `Ord`.

**Pull request closed without merging**
