### PR TITLE
Add more electromagnetism-related units.

### PR DESCRIPTION
**Pull request by Aehmlo**
This PR adds a bunch of electromagnetism-related goodies, including
* luminance (cd/m²)
* capacitance (F)
* inductance (H)
* electrical resistance (Ω)
* magnetic flux (Wb)
* magnetic flux density (T)
* electrical conductance (S)
* and electric charge (C).

(I'm certain that the build will fail on Travis with this many quantities, but it passes locally.)

### CODE REVIEW

**Comment by iliekturtles** [comment]
I pushed some additional changes to `master` to speed up the build and hopefully stop the timeouts on 1.20.0. Can you rebase these changes to see if they still pass?

I have a busy weekend coming up so a full review for all the changes here likely will be next week.

**Comment by iliekturtles** [comment]
- Luminance
  - Looks good!
- Capacitance
  - Wrap quantity documentation at 100 characters.
- Inductance
  - Correct documentation: kg⋅m2⋅s−2⋅A−2. Looks like documentation is currently copied from Capacitance.
  - Wrap quantity documentation at 100 characters.
- Electrical resistance
  - Looks good!
- Magnetic flux
  - Looks good!
- Magnetic flux density
  - Looks good!
- Electrical conductance
  - Abbreviation for `abmho` references siemens.
  - Abbreviation and descriptions for `statmho` references siemens.
  - Wrap check_dimension at 100 characters.
  - Add tests for `abmho` and `statmho`.
- Electric charge
  - Looks good!

**Comment by Aehmlo** [comment]
Bump

**Comment by iliekturtles** [comment]
Welcome back. Hope finals went well!

Couple minor formatting fixes and correction of the singular description for statmho. Once these changes are applied I'll merge!

```diff
diff --git a/src/si/capacitance.rs b/src/si/capacitance.rs
index 37c0740..7ba7a8f 100644
--- a/src/si/capacitance.rs
+++ b/src/si/capacitance.rs
@@ -1,9 +1,8 @@
-//! Capacitance
-//! (base unit farad, m<sup>-2</sup> · kg<sup>-1</sup> · s<sup>4</sup> · A<sup>2</sup>).
+//! Capacitance (base unit farad, m<sup>-2</sup> · kg<sup>-1</sup> · s<sup>4</sup> · A<sup>2</sup>).
 
 quantity! {
-    /// Capacitance (base unit farad,
-    /// m<sup>-2</sup> · kg<sup>-1</sup> · s<sup>4</sup> · A<sup>2</sup>).
+    /// Capacitance (base unit farad, m<sup>-2</sup> · kg<sup>-1</sup> · s<sup>4</sup> ·
+    /// A<sup>2</sup>).
     quantity: Capacitance; "capacitance";
     /// Capacitance dimension, m<sup>-2</sup> · kg<sup>-1</sup> · s<sup>4</sup> · A<sup>2</sup>.
     dimension: ISQ<
diff --git a/src/si/electrical_conductance.rs b/src/si/electrical_conductance.rs
index 5d05987..86ae2b5 100644
--- a/src/si/electrical_conductance.rs
+++ b/src/si/electrical_conductance.rs
@@ -43,7 +43,7 @@ quantity! {
         @abmho: 1.0_E9; "abmho", "abmho", "abmhos";
         @absiemens: 1.0_E9; "abS", "abmsiemens", "abmsiemens";
         @statsiemens: 1.112_650_E-12; "statS", "statsiemens", "statsiemens";
-        @statmho: 1.112_650_E-12; "statmho", "statmhos", "statmhos";
+        @statmho: 1.112_650_E-12; "statmho", "statmho", "statmhos";
     }
 }
 
diff --git a/src/si/inductance.rs b/src/si/inductance.rs
index 30876d8..d0e0e4b 100644
--- a/src/si/inductance.rs
+++ b/src/si/inductance.rs
@@ -1,7 +1,8 @@
 //! Inductance (base unit henry, m<sup>2</sup> · kg<sup>1</sup> · s<sup>-2</sup> · A<sup>-2</sup>).
 
 quantity! {
-    /// Inductance (base unit henry, m<sup>2</sup> · kg<sup>1</sup> · s<sup>-2</sup> · A<sup>-2</sup>).
+    /// Inductance (base unit henry, m<sup>2</sup> · kg<sup>1</sup> · s<sup>-2</sup> ·
+    /// A<sup>-2</sup>).
     quantity: Inductance; "inductance";
     /// Inductance dimension, m<sup>2</sup> · kg<sup>1</sup> · s<sup>-2</sup> · A<sup>-2</sup>.
     dimension: ISQ<
```

**Comment by iliekturtles** [comment]
For some reason one of the comment changes didn't apply:

```diff
diff --git a/src/si/capacitance.rs b/src/si/capacitance.rs
index 775d038..7ba7a8f 100644
--- a/src/si/capacitance.rs
+++ b/src/si/capacitance.rs
@@ -1,7 +1,8 @@
 //! Capacitance (base unit farad, m<sup>-2</sup> · kg<sup>-1</sup> · s<sup>4</sup> · A<sup>2</sup>).

 quantity! {
-    /// Capacitance (base unit farad, m<sup>-2</sup> · kg<sup>-1</sup> · s<sup>4</sup> · A<sup>2</sup>).
+    /// Capacitance (base unit farad, m<sup>-2</sup> · kg<sup>-1</sup> · s<sup>4</sup> ·
+    /// A<sup>2</sup>).
     quantity: Capacitance; "capacitance";
     /// Capacitance dimension, m<sup>-2</sup> · kg<sup>-1</sup> · s<sup>4</sup> · A<sup>2</sup>.
     dimension: ISQ<
```

**Comment by Aehmlo** [comment]
That's odd; I very specifically remembering authoring that commit. Maybe I dropped it instead of squashing it. Regardless, it's fixed now and I think this can finally be merged!

**Comment by iliekturtles** [comment]
Merged. Thanks!

**Pull request merged**
