### PR TITLE
Thermal conductance

### PR DESCRIPTION
**Pull request by calbaker**
I'm pretty sure I got this right.  I need thermal conductance [W/K] for a number of projects I'm working on so I thought I'd try a PR.  Let me know if anything important needs attention.  Please check my work!

### CODE REVIEW

**Comment by iliekturtles** [comment]
Thanks for the PR! Changes look really good. I pushed some minor fixes to your branch Mostly formatting. Please review and squash everything down to one commit. Test suite is running now.

**Comment by calbaker** [comment]
> Please review and squash everything down to one commit. 

@iliekturtles, I think we're all set!  

BTW, your user name is great.  My wife and I have saved numerous snapping turtles that were crossing roads by helping them across and blocking traffic.

**Comment by iliekturtles** [comment]
Could you also update the commit message on the squashed commit. Something like `Add thermal conductance quantity.` as the title and a short description of the quantity if desired.

**Comment by calbaker** [comment]
@iliekturtles , should be all set now!

**Comment by iliekturtles** [comment]
Merged. Thanks!

**Pull request merged**
