### PR TITLE
[WIP] Add Github Actions CI

### LINKED ISSUE #223: Fix issues with uom CI process
I recently discovered a number of issues with the current Travis CI process. These issues have let a number of regressions slip through. I have fixed some in a57f4b5dc687cd09729a1befbfd895c4d8cc9abb and 4d820e5ffa4ca6415757b610d0ef0c5f48d0d8dd. I have additional changes I'm working on to resolve failures seen here: https://travis-ci.org/github/iliekturtles/uom/jobs/742299009

 * Builds not executing for PRs
 * Builds executing after a significant delay.
 * Builds not responding cancel requests.
 * Travis CI made changes that caused the `exclude` keyword to start causing explicitly specified jobs to be skipped. This caused the most import test job to be skipped.
 * Code coverage is not being reported.

How should the issues be fixed?

 * Fix Travis CI issues?
 * Switch to GitHub actions (https://github.com/actions-rs)?
 * Switch to another CI provider? Azure?

### PR DESCRIPTION
**Pull request by CreepySkeleton**
Closes #223 

### Caching 

Worst case CI time of cache-hit builds is about ~10 mins. Worst case CI time of cache-miss builds is about 17-20 mins. If I remove cache entirely, CI time is about ~15-17 minutes. I will continue experimenting with it tomorrow.

(Do keep in mind that GH actions has no "drop all cache" button.)

### Tarpaulin & codecov reports

I've set it to trigger only on pushes but not on PRs. Works fine, CI time is about 7-9 minutes.

(You'll need to set up the `CODECOV_TOKEN` secret)

### Windows & MacOs builds

Works remarkably well.

### Features 

I had been trying to get `--all-features` build to work, but eventually gave up and copy-pasted cargo commands from travis. I will continue experimenting on it tomorrow.

### Beta & Nightly & MSRV

They are currently run only with default features check (copy-pasted from your travis setup). I will be investigating it further, but I suspect that some of your tests are kinda sorta broken (they don't even compile on beta or nightly or 1.37).

### CODE REVIEW

**Comment by CreepySkeleton** [comment]
### Clippy & Rustfmt

CI time is about 4-5 mins. Looks OK to me, but I think it can be reduced further if need be.

**Comment by CreepySkeleton** [comment]
Oh, doesn't seem like this Pr triggered any builds. You can see some results in my fork:

https://github.com/CreepySkeleton/uom/actions/runs/389985942
https://github.com/CreepySkeleton/uom/actions/runs/389985941
https://github.com/CreepySkeleton/uom/actions/runs/389985940
https://github.com/CreepySkeleton/uom/actions/runs/389985939

**Comment by CreepySkeleton** [comment]
Example PR in my repo: https://github.com/CreepySkeleton/uom/pull/1

**Comment by iliekturtles** [comment]
Excellent! Thanks for the PR. I'll start reviewing later today or tomorrow.

**Comment by iliekturtles** [comment]
I haven't forgotten about this, just ended up having a really busy weekend. Is there anything still WIP or do you believe this is just about ready to go?

**Comment by iliekturtles** [comment]
Thanks again for submitting this PR! I made some changes (see details in my commit) and merged. Really excited to have the quicker CI times again.

**Comment by CreepySkeleton** [comment]
Ugh, sorry for my unresponsiveness, had a busy week too. I am firm in my belief that it's a world-wide conspiracy run by nefarious coffee manufacturers: the busier the programmers are, the more coffee they consume. The doctors likely have their cut of the deal as well.

I think I've got the caching wrong: GH caching works differently from Travis'. The current script will keep pulling the old build artifacts until the next rustc version is released, and that may make the CI time to gradually regress. Hopefully, I'll look into this sometime next week, unless I'll be busy running my own anti-conspiracy conspiracy, overrunning the existing cartels and mandating that every programmer has a limitless supply of free coffee. Anime fans will pay for it, they'll pay for anything if you promise them that every programming company is obliged to host cosplay events from there on.

**Comment by iliekturtles** [comment]
Glad you caught that! I went to review what actions-rs does and it looks like they don't have a cache action yet. https://github.com/Swatinem/rust-cache is asking about the possibility of inclusion

**Comment by iliekturtles** [comment]
Also looks like when I push to a PR branch the actions get executed twice:

image

**Comment by CreepySkeleton** [comment]
One is triggered by "push", the other by "PR" part. I'll see what we can do next week.

**Pull request merged**
