### PR TITLE
Added trait implementations to ParseQuantityError

### PR DESCRIPTION
**Pull request by Lucretiel**

### CODE REVIEW

**Comment by iliekturtles** [comment]
Thanks for the PR! I'm planning to review this weekend.

**Comment by iliekturtles** [comment]
Couple minor fixes. If you can review, apply, and then squash your commits I'll merge!

 * `use` statements can be simplified slightly. `uom` exposes a `lib` module to handle `std` vs. `core`.
 * `UnknownUnit` message wording didn't make sense to me. I changed to a possible wording I thought made more sense.

```patch
diff --git a/src/lib.rs b/src/lib.rs
index 29115c9..efc91d4 100644
--- a/src/lib.rs
+++ b/src/lib.rs
@@ -621,10 +621,7 @@ pub mod fmt {

 /// Unicode string slice manipulation for quantities.
 pub mod str {
-    use core::fmt::{self, Display, Formatter};
-
-    #[cfg(feature = "std")]
-    use std::error::Error;
+    use crate::lib::fmt::{self, Display, Formatter};

     /// Represents an error encountered while parsing a string into a `Quantity`.
     #[allow(missing_copy_implementations)]
@@ -654,11 +651,11 @@ pub mod str {
             match *self {
                 NoSeparator => write!(f, "no space between quantity and units"),
                 ValueParseError => write!(f, "error parsing unit quantity"),
-                UnknownUnit => write!(f, "unrecognized parsing unit of measure"),
+                UnknownUnit => write!(f, "unrecognized unit of measure"),
             }
         }
     }

     #[cfg(feature = "std")]
-    impl Error for ParseQuantityError {}
+    impl crate::lib::error::Error for ParseQuantityError {}
 }
```

**Comment by Lucretiel** [comment]
Thanks for the review! Been busy, will follow up this weekend

**Comment by iliekturtles** [comment]
I ended up applying the patch along with `assert_all_impl`/`assert_not_impl_any` tests. I'm waiting on build results and will plan on merging unless there was anything else you found.

**Comment by iliekturtles** [comment]
Manually merged. Thanks so much for the PR!

**Pull request closed without merging**
