### PR TITLE
Add additional units.

### PR DESCRIPTION
**Pull request by Aehmlo**
This adds more units for the below quantities.

- Mass (#2)
- Velocity (#5)
- Area (#6)
- Force (#8)
- Acceleration (#9)
- Volume (#7)

This pull request does not include additional tests, as I was unsure of the desired format for these; with some guidance, I'd be more than willing to implement some tests.

Conversion factors are taken directly from [NIST Special Publication 811](https://www.nist.gov/pml/nist-guide-si-appendix-b9-factors-units-listed-kind-quantity-or-field-science).

### CODE REVIEW

**Comment by iliekturtles** [comment]
Awesome! Thanks for all these extra units. I plan to review tomorrow and will let you know if I find anything. I'm not too worried about tests at this point. I have some experiments to improve things in the [`dev-tests`](https://github.com/iliekturtles/uom/tree/dev-tests) branch.

**Comment by iliekturtles** [comment]
- General
  - Rebase any changes noted below into the original commits.
  - Rebase e5e6ea83, whitespace errors, into the earlier commits that affect area/mass/velocity.
  - Change number formatting so that `E` is preceded by an `_`: `2.0_E-4`.
- Mass
  - Do you have a reference for hundredweight (long)'s abbreviation? The only thing I could find was `cwt long`, and the [source](http://www.traditionaloven.com/culinary-arts/weight/convert-hundredweight-cwt-short-us-to-hundredweight-cwt-long-uk.html) wasn't authoritative.
  - Rename `ounce_apothecary` to `ounce_troy`. Apothecaries' seems to be [obsolete](https://en.wikipedia.org/wiki/Ounce#Apothecaries'_ounce). abbrev/desc: `"oz t", "troy ounce", "troy ounces";`
  - Rename `pound_apothecary` to `pound_troy`.
  - Change `ton_long`'s abbreviation to `2240 lb`.
  - Change `ton_short`'s abbreviation to `2000 lb`.
  - Change the comment at the end of the `ton` line to `// ton, metric.`
- Velocity
  - Correct `foot_per_minute` and `foot_per_second`'s abbreviations: `ft/min`, `ft/s`.
  - Change `mile_per_hour`'s conversion factor to `4.470_4_E-1`.
- Area
  - `cmil` seems to be the more generally used abbreviation for `circular_mil`.
  - Change `square_inch`'s conversion factor to `6.451_6_E-4`.
  - Change `ton_force`'s abbreviation to `2000 lbf`.
- Volume
  - Ran out of time. Will get to this next.

**Comment by iliekturtles** [comment]
- Acre
  - Change `acre`'s abbreviation to `ac`.
- Volume
  - Change `acre_foot`'s abbreviation to `ac · ft`.
  - Change `gill_imperial`'s abbreviation to `gi (UK)`.
  - Change `gill`'s abbreviation to `gi`.
  - Ounce / fluid ounce is duplicated. I suggest removing `ounce` / `ounce_imperial` and changing `fluid_ounce` / `fluid_ounce_imperial` as follows:
    - Change `fluid_ounce_imperial`'s abbreviation to `fl oz (UK)`.
    - Change `fluid_ounce`'s abbreviation to `fl oz`.
  - Change `pint_dry`'s abbreviation to `dry pt`.
  - Change `print_liquid`'s abbreviation to `liq pt`.
  - Change `quart_dry`'s abbreviation to `dry qt`.
  - Change `quart_liquid`'s abbreviation to `liq qt`.

**Comment by Aehmlo** [comment]
Fixed.

Re: long hundredweight — my source was even more dubious than yours, so I went with what yours suggested.

Sorry to create so much more work for you — should've reviewed this a little more closely before sending the pull request.

**Comment by iliekturtles** [comment]
Thanks so much for all this work! Don't worry about the review time, it wasn't nearly what adding the units was. Adding new units is a tough process and a second set of eyes always finds something.

**Pull request merged**
