### PR TITLE
Fix some clippy lints

### PR DESCRIPTION
**Pull request by hellow554**
I really love clippy and I ran it so see if anything can be improved.
But the very first things was an clippy error that I saw, so I looked at it and decided that that error is acceptable and can be allowed.

This PR is read best per commit.
If you like I can purge certain commits and/or split them into seperate PRs.

### CODE REVIEW

**Comment by iliekturtles** [comment]
Thanks for the PR! Did you run `clippy` with extra parameters to get the `Self` warnings? I kicked off tests and there are some errors, could you review?

**Comment by hellow554** [comment]
> with extra parameters to get the Self warnings

yes, indeed: `cargo clippy -- -Wclippy::pedantic -Wclippy::nursery`

I'll look into the CI errors, give me a minute :)

**Comment by hellow554** [comment]
Yeah... I was not sure about the `unit` field in that struct.
I thought it was a too big issue to remove it, but I can give it a try

**Comment by hellow554** [comment]
I did something, it works on my machine, let's hope it gets through CI

**Comment by hellow554** [comment]
> package `memchr v2.6.4` cannot be built because it requires rustc 1.61 or newer, while the currently active rustc version is 1.60.0

:( Not my fault, but I can try to fix it, if you like

**Comment by iliekturtles** [comment]
Sorry for the extended delay! Go ahead and add a commit to bump the MSRV to 1.61.0. You can model the commit after 86407300a60bdb1a968dfa97568bccec199b3218.

**Comment by iliekturtles** [comment]
I just realized the 1.61.0 requirement is causing a problem in master right now and isn't from this PR. The MSRV bump should be separate if you get a chance to submit a new PR before I can get it fixed.

**Comment by hellow554** [comment]
@iliekturtles  I opened #456 Please have a look :)

**Comment by iliekturtles** [comment]
Thanks again for this PR. I just merged! I went through doing a final review. I made some minor edits to the commit messages and a couple fixes to the code.

**Comment by hellow554** [comment]
Sure enough! Thanks for the merge

**Pull request merged**
