### PR TITLE
Update dependency

### PR DESCRIPTION
**Pull request by remilauzier**
There's a bunch of warning about deprecate use of Rational but everything compile fine and i have seen no regression in test on my computer.

### CODE REVIEW

**Comment by iliekturtles** [comment]
Thanks so much for the PR!

I'd like to see the deprecation warnings resolved. I believe if you apply the following diff that should do the trick. I'm reviewing `uom` documentation to see if any other references need to be updated and will report back when I'm done.

I added #255 to deny warnings like this. If you hadn't mentioned it I wouldn't have realized that the warnings existed!

```diff
diff --git a/src/lib.rs b/src/lib.rs
index 17ef3d8..a570486 100644
--- a/src/lib.rs
+++ b/src/lib.rs
@@ -271,7 +271,7 @@ pub mod num {
     pub use num_bigint::{BigInt, BigUint};

     #[cfg(feature = "rational-support")]
-    pub use num_rational::Rational;
+    pub type Rational = num_rational::Ratio<isize>;

     #[cfg(feature = "bigint-support")]
     pub use num_rational::BigRational;
```

**Comment by iliekturtles** [comment]
Everything else looks good. If you can review and apply the diff in my last comment I think we'll be good to merge.

**Comment by iliekturtles** [comment]
Could you squash your commits into a single commit?

**Comment by remilauzier** [comment]
Sorry i ujst seem to can't squash them correctly. Github seem to have an option on your end, or i could just redo the pr.
https://github.blog/2016-04-01-squash-your-commits/

**Comment by iliekturtles** [comment]
If you're using the command line you can squash your commits together using `git rebase -i master`. `r`eword the first commit to make sure you have a good commit message and then `f`ixup the rest.

**Comment by remilauzier** [comment]
It just write ``noop`` on my end.

**Comment by iliekturtles** [comment]
Try `git rebase -i origin/master`. If that isn't working then I can manually merge.

**Comment by remilauzier** [comment]
Same thing. it write ¨noop¨. it seem it didn't like to squash commit after havinf been merge in a branch.

**Comment by iliekturtles** [comment]
No problem! I manually merged. Thanks so much for the PR!

**Pull request closed without merging**
